"""empty message

Revision ID: 5130402611a9
Revises: 52a62684331b
Create Date: 2023-03-11 22:58:01.871828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5130402611a9'
down_revision = '52a62684331b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('recognition_ready', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faces', 'recognition_ready')
    # ### end Alembic commands ###
