"""add dept cols - ori, fips, etc

Revision ID: 85c80efd1bb9
Revises: c3d19b3ddbd2
Create Date: 2023-10-25 14:19:50.448848

"""
from alembic import op
import sqlalchemy as sa



revision = '85c80efd1bb9'
down_revision = 'c3d19b3ddbd2'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('locality_fips', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ori', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('narrative', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('narrative')
        batch_op.drop_column('ori')
        batch_op.drop_column('locality_fips')
        batch_op.drop_column('type_code')
        batch_op.drop_column('state_id')
        batch_op.drop_column('county')

    # ### end Alembic commands ###
