"""remove sheet detail fks

Revision ID: 3bf4b2e7d54e
Revises: a18625c2511c
Create Date: 2023-06-22 16:30:02.969025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf4b2e7d54e'
down_revision = 'a18625c2511c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('import_sheet_details_unit_id_fkey', 'import_sheet_details', type_='foreignkey')
    op.drop_constraint('import_sheet_details_job_id_fkey', 'import_sheet_details', type_='foreignkey')
    op.drop_constraint('import_sheet_details_department_id_fkey', 'import_sheet_details', type_='foreignkey')
    op.drop_constraint('import_sheet_details_officer_id_fkey', 'import_sheet_details', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('import_sheet_details_officer_id_fkey', 'import_sheet_details', 'officers', ['officer_id'], ['id'])
    op.create_foreign_key('import_sheet_details_department_id_fkey', 'import_sheet_details', 'departments', ['department_id'], ['id'])
    op.create_foreign_key('import_sheet_details_job_id_fkey', 'import_sheet_details', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key('import_sheet_details_unit_id_fkey', 'import_sheet_details', 'unit_types', ['unit_id'], ['id'])
    # ### end Alembic commands ###
