"""import sheets v3

Revision ID: a18625c2511c
Revises: ffd8a4f8a558
Create Date: 2023-06-22 14:17:24.551559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18625c2511c'
down_revision = 'ffd8a4f8a558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('hash_sheet', sa.String(length=120), nullable=True),
    sa.Column('date_inserted', sa.DateTime(), nullable=True),
    sa.Column('date_loaded', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('column_mapping', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_sheet_details',
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_initial', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('badge_number', sa.String(), nullable=True),
    sa.Column('rank_title', sa.String(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('employment_date', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('salary_overtime', sa.String(), nullable=True),
    sa.Column('salary_year', sa.String(), nullable=True),
    sa.Column('salary_is_fy', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['import_sheets.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_types.id'], ),
    sa.PrimaryKeyConstraint('sheet_id', 'row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_sheet_details')
    op.drop_table('import_sheets')
    # ### end Alembic commands ###
