"""add Contributor role to Users

Revision ID: 764cfc5047ca
Revises: 4601de3bcca0
Create Date: 2024-12-01 23:36:01.564593

"""
from alembic import op
import sqlalchemy as sa



revision = '764cfc5047ca'
down_revision = '4601de3bcca0'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dup_officer_matches', schema=None) as batch_op:
        batch_op.alter_column('id_1',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('id_2',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('match_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               nullable=False)
        batch_op.drop_index('ix_dup_officer_matches_id_1')
        batch_op.drop_index('ix_dup_officer_matches_id_2')
        batch_op.create_index(batch_op.f('ix_dup_officer_matches_match_score'), ['match_score'], unique=False)
        batch_op.create_foreign_key(None, 'officers', ['id_2'], ['id'])
        batch_op.create_foreign_key(None, 'officers', ['id_1'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_contributor', sa.Boolean(), nullable=True))
        
    # kf - set all admins and ACs as contribs
    op.execute('update users set is_contributor = (is_administrator or is_area_coordinator)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_contributor')

    with op.batch_alter_table('dup_officer_matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dup_officer_matches_match_score'))
        batch_op.create_index('ix_dup_officer_matches_id_2', ['id_2'], unique=False)
        batch_op.create_index('ix_dup_officer_matches_id_1', ['id_1'], unique=False)
        batch_op.alter_column('match_score',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('id_2',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('id_1',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
