"""dup officer match fks

Revision ID: 4601de3bcca0
Revises: 99beaeea8e2e
Create Date: 2024-03-09 17:46:51.927023

"""
from alembic import op
import sqlalchemy as sa



revision = '4601de3bcca0'
down_revision = '99beaeea8e2e'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dup_officer_matches', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'officers', ['id_1'], ['id'])
        batch_op.create_foreign_key(None, 'officers', ['id_2'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dup_officer_matches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
