"""add cases and link to officers, depts

Revision ID: efadca814703
Revises: 85c80efd1bb9
Create Date: 2024-01-30 02:03:41.076186

"""
from alembic import op
import sqlalchemy as sa



revision = 'efadca814703'
down_revision = '85c80efd1bb9'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court_code', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('filing_nature', sa.String(), nullable=True),
    sa.Column('code_section', sa.String(), nullable=True),
    sa.Column('plaintiff', sa.String(), nullable=True),
    sa.Column('defendant', sa.String(), nullable=True),
    sa.Column('disposition', sa.String(), nullable=True),
    sa.Column('judgment', sa.String(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('case_link', sa.String(), nullable=True),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.Column('pacer_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_cases',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='department_lawsuits_case_id_fkey'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='department_lawsuits_department_id_fkey'),
    sa.PrimaryKeyConstraint('department_id', 'case_id')
    )
    op.create_table('officer_cases',
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='officer_lawsuits_case_id_fkey'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], name='officer_lawsuits_officer_id_fkey'),
    sa.PrimaryKeyConstraint('officer_id', 'case_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officer_cases')
    op.drop_table('department_cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
