"""add dup_officer_matches table

Revision ID: 99beaeea8e2e
Revises: efadca814703
Create Date: 2024-03-09 17:16:25.951822

"""
from alembic import op
import sqlalchemy as sa



revision = '99beaeea8e2e'
down_revision = 'efadca814703'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dup_officer_matches',
    sa.Column('id_1', sa.Integer(), nullable=False),
    sa.Column('id_2', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_1', 'id_2')
    )
    with op.batch_alter_table('dup_officer_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dup_officer_matches_match_score'), ['match_score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dup_officer_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dup_officer_matches_match_score'))

    op.drop_table('dup_officer_matches')
    # ### end Alembic commands ###
