"""empty message

Revision ID: cf036b56e20d
Revises: 93fc3e074dcc
Create Date: 2023-03-02 02:31:23.817982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf036b56e20d'
down_revision = '93fc3e074dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'department_id')
    # ### end Alembic commands ###
