"""empty message

Revision ID: e79b345d0eef
Revises: 52a62684331b
Create Date: 2023-03-11 21:26:53.877348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79b345d0eef'
down_revision = '52a62684331b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('recog_processed', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('faces', 'face_processed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faces', sa.Column('face_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('faces', 'recog_processed')
    # ### end Alembic commands ###
